# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from summit_description/IMU_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IMU_info(genpy.Message):
  _md5sum = "e7c9a9f8e0a07a58ffaffcfcf8fbe485"
  _type = "summit_description/IMU_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 roll
float64 pitch
float64 yaw

float64 x
float64 y
float64 z

float64 linaccx
float64 linaccy
float64 linaccz
"""
  __slots__ = ['roll','pitch','yaw','x','y','z','linaccx','linaccy','linaccz']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roll,pitch,yaw,x,y,z,linaccx,linaccy,linaccz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMU_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.linaccx is None:
        self.linaccx = 0.
      if self.linaccy is None:
        self.linaccy = 0.
      if self.linaccz is None:
        self.linaccz = 0.
    else:
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.linaccx = 0.
      self.linaccy = 0.
      self.linaccz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.roll, _x.pitch, _x.yaw, _x.x, _x.y, _x.z, _x.linaccx, _x.linaccy, _x.linaccz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.roll, _x.pitch, _x.yaw, _x.x, _x.y, _x.z, _x.linaccx, _x.linaccy, _x.linaccz,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.roll, _x.pitch, _x.yaw, _x.x, _x.y, _x.z, _x.linaccx, _x.linaccy, _x.linaccz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.roll, _x.pitch, _x.yaw, _x.x, _x.y, _x.z, _x.linaccx, _x.linaccy, _x.linaccz,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
