// Generated by gencpp from file summit_description/IMU_info.msg
// DO NOT EDIT!


#ifndef SUMMIT_DESCRIPTION_MESSAGE_IMU_INFO_H
#define SUMMIT_DESCRIPTION_MESSAGE_IMU_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace summit_description
{
template <class ContainerAllocator>
struct IMU_info_
{
  typedef IMU_info_<ContainerAllocator> Type;

  IMU_info_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , linaccx(0.0)
    , linaccy(0.0)
    , linaccz(0.0)  {
    }
  IMU_info_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , linaccx(0.0)
    , linaccy(0.0)
    , linaccz(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _linaccx_type;
  _linaccx_type linaccx;

   typedef double _linaccy_type;
  _linaccy_type linaccy;

   typedef double _linaccz_type;
  _linaccz_type linaccz;





  typedef boost::shared_ptr< ::summit_description::IMU_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::summit_description::IMU_info_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_info_

typedef ::summit_description::IMU_info_<std::allocator<void> > IMU_info;

typedef boost::shared_ptr< ::summit_description::IMU_info > IMU_infoPtr;
typedef boost::shared_ptr< ::summit_description::IMU_info const> IMU_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::summit_description::IMU_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::summit_description::IMU_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace summit_description

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'summit_description': ['/home/rahul/mecanum_ws/src/summit_description/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::summit_description::IMU_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::summit_description::IMU_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_description::IMU_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::summit_description::IMU_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_description::IMU_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::summit_description::IMU_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::summit_description::IMU_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7c9a9f8e0a07a58ffaffcfcf8fbe485";
  }

  static const char* value(const ::summit_description::IMU_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7c9a9f8e0a07a58ULL;
  static const uint64_t static_value2 = 0xffaffcfcf8fbe485ULL;
};

template<class ContainerAllocator>
struct DataType< ::summit_description::IMU_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "summit_description/IMU_info";
  }

  static const char* value(const ::summit_description::IMU_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::summit_description::IMU_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
float64 linaccx\n\
float64 linaccy\n\
float64 linaccz\n\
";
  }

  static const char* value(const ::summit_description::IMU_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::summit_description::IMU_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.linaccx);
      stream.next(m.linaccy);
      stream.next(m.linaccz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMU_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::summit_description::IMU_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::summit_description::IMU_info_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "linaccx: ";
    Printer<double>::stream(s, indent + "  ", v.linaccx);
    s << indent << "linaccy: ";
    Printer<double>::stream(s, indent + "  ", v.linaccy);
    s << indent << "linaccz: ";
    Printer<double>::stream(s, indent + "  ", v.linaccz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUMMIT_DESCRIPTION_MESSAGE_IMU_INFO_H
